"""add_twelve_labs_index_table

Revision ID: 08da52bb79c6
Revises: 8b5c080bab25
Create Date: 2026-01-07 21:43:19.397290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08da52bb79c6'
down_revision = '8b5c080bab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twelve_labs_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('session', sa.Column('indexed_asset_id', sa.String(), nullable=True))
    op.add_column('session', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('session', sa.Column('analysis_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'analysis_data')
    op.drop_column('session', 'question')
    op.drop_column('session', 'indexed_asset_id')
    op.drop_table('twelve_labs_index')
    # ### end Alembic commands ###
