"""add templates/questions/grades/sessions

Revision ID: 461d2e04c93e
Revises: bc726b00803a
Create Date: 2025-11-22 20:54:47.299218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461d2e04c93e'
down_revision = 'bc726b00803a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
