"""add templates/questions/grades/sessions

Revision ID: 760a524c7095
Revises: 3706c50a27a9
Create Date: 2025-11-19 13:39:39.341888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760a524c7095'
down_revision = '3706c50a27a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point', sa.Text(), nullable=False),
    sa.Column('ways_to_improve', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'GRADED', name='sessionstate'), nullable=False),
    sa.Column('overall_grade', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_language_score', sa.Integer(), nullable=False),
    sa.Column('speech_score', sa.Integer(), nullable=False),
    sa.Column('material_score', sa.Integer(), nullable=False),
    sa.Column('brevity_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    op.drop_table('session')
    op.drop_table('question')
    op.drop_table('template')
    op.drop_table('feedback')
    # ### end Alembic commands ###
