"""TL integration

Revision ID: 825037547798
Revises: 8b5c080bab25
Create Date: 2026-02-24 18:26:57.733241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '825037547798'
down_revision = '8b5c080bab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twelve_labs_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_column('session', 'state')
    op.execute("DROP TYPE IF EXISTS sessionstate")
    op.execute(
        "CREATE TYPE componentstate AS ENUM "
        "('PENDING', 'INDEXING', 'ANALYZING', 'COMPLETED', 'ERROR')"
    )
    op.execute(
        "ALTER TABLE session_component ADD COLUMN state componentstate "
        "NOT NULL DEFAULT 'PENDING'::componentstate"
    )
    op.add_column('session_component', sa.Column('indexed_asset_id', sa.String(), nullable=True))
    op.execute("DROP TYPE IF EXISTS sessionstate")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$ BEGIN "
        "IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sessionstate') THEN "
        "CREATE TYPE sessionstate AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'GRADED'); "
        "END IF; END $$"
    )
    op.execute(
        "ALTER TABLE session ADD COLUMN state sessionstate "
        "NOT NULL DEFAULT 'PENDING'::sessionstate"
    )
    op.drop_column('session_component', 'indexed_asset_id')
    op.drop_column('session_component', 'state')
    op.drop_table('twelve_labs_index')
    postgresql.ENUM('PENDING', 'INDEXING', 'ANALYZING', 'COMPLETED', 'ERROR', name='componentstate').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
