"""Add session component

Revision ID: 8b5c080bab25
Revises: 461d2e04c93e
Create Date: 2026-01-07 03:13:29.309815

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8b5c080bab25'
down_revision = '461d2e04c93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'session_component',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('transcript', sa.Text(), nullable=True),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['question.id'],
        ),
        sa.ForeignKeyConstraint(
            ['session_id'],
            ['session.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'video',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('s3_key', sa.String(), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('checksum', sa.String(), nullable=True),
        sa.Column('session_component_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['session_component_id'],
            ['session_component.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_component_id'),
    )
    op.add_column('feedback', sa.Column('session_component_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'feedback', ['session_component_id'])
    op.create_foreign_key(None, 'feedback', 'session_component', ['session_component_id'], ['id'])
    op.add_column('grade', sa.Column('session_component_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'grade', ['session_component_id'])
    op.drop_constraint(op.f('grade_session_id_fkey'), 'grade', type_='foreignkey')
    op.drop_constraint(op.f('grade_feedback_id_fkey'), 'grade', type_='foreignkey')
    op.create_foreign_key(None, 'grade', 'session_component', ['session_component_id'], ['id'])
    op.drop_column('grade', 'feedback_id')
    op.drop_column('grade', 'overall_score')
    op.drop_column('grade', 'session_id')
    op.drop_column('session', 'video_url')
    op.drop_column('session', 'transcript')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('session', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('grade', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('grade', sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('grade', sa.Column('feedback_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grade', type_='foreignkey')
    op.create_foreign_key(op.f('grade_feedback_id_fkey'), 'grade', 'feedback', ['feedback_id'], ['id'])
    op.create_foreign_key(op.f('grade_session_id_fkey'), 'grade', 'session', ['session_id'], ['id'])
    op.drop_constraint(None, 'grade', type_='unique')
    op.drop_column('grade', 'session_component_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='unique')
    op.drop_column('feedback', 'session_component_id')
    op.drop_table('video')
    op.drop_table('session_component')
    # ### end Alembic commands ###
