"""TL_integration

Revision ID: 9685e61a642f
Revises: 8b5c080bab25
Create Date: 2026-02-23 20:30:22.847529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9685e61a642f'
down_revision = '8b5c080bab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twelve_labs_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.execute("ALTER TYPE sessionstate ADD VALUE IF NOT EXISTS 'INDEXING'")
    op.execute("ALTER TYPE sessionstate ADD VALUE IF NOT EXISTS 'ANALYZING'")
    op.execute("ALTER TYPE sessionstate ADD VALUE IF NOT EXISTS 'ERROR'")
    op.drop_column('session', 'state')
    op.add_column('session_component', sa.Column('state', sa.Enum('PENDING', 'INDEXING', 'ANALYZING', 'COMPLETED', 'ERROR', name='sessionstate'), nullable=False))
    op.add_column('session_component', sa.Column('indexed_asset_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_component', 'indexed_asset_id')
    op.drop_column('session_component', 'state')
    op.add_column('session', sa.Column('state', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'GRADED', 'INDEXING', 'ANALYZING', 'ERROR', name='sessionstate'), autoincrement=False, nullable=False))
    op.drop_table('twelve_labs_index')
    # ### end Alembic commands ###
