"""Init auth

Revision ID: bc726b00803a
Revises:
Create Date: 2025-11-05 02:45:03.579823

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'bc726b00803a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('salt', sa.String(), nullable=True),
        sa.Column('verification_token', sa.Integer(), nullable=False),
        sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'user_message_delay',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('delay_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('user_email', sa.String(), nullable=False),
        sa.Column('user_ip', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_session',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
        sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_session')
    op.drop_table('user_message_delay')
    op.drop_table('user')
    # ### end Alembic commands ###
