"""TL_integration

Revision ID: f83558e79b26
Revises: 8b5c080bab25
Create Date: 2026-02-23 20:02:08.967192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f83558e79b26'
down_revision = '8b5c080bab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twelve_labs_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(), nullable=False),
    sa.Column('create_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('video')
    op.drop_column('session', 'state')
    op.add_column('session_component', sa.Column('state', sa.Enum('pending', 'indexing', 'analyzing', 'completed', 'error', name='sessionstate'), nullable=False))
    op.add_column('session_component', sa.Column('indexed_asset_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_component', 'indexed_asset_id')
    op.drop_column('session_component', 'state')
    op.add_column('session', sa.Column('state', postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'GRADED', name='sessionstate'), autoincrement=False, nullable=False))
    op.create_table('video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_component_id'], ['session_component.id'], name=op.f('video_session_component_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('video_pkey')),
    sa.UniqueConstraint('session_component_id', name=op.f('video_session_component_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('twelve_labs_index')
    # ### end Alembic commands ###
